import type { Category } from "@/features/categories/types";

export const defaultCategories: Category[] = [
  {
    id: 1,
    name: "دسته‌بندی‌نشده",
    slug: "uncategorized",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/uncategorized/",
  },
  {
    id: 2,
    name: "ادویه جات",
    slug: "spices",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/spices/",
  },
  {
    id: 3,
    name: "قاشق و چنگال",
    slug: "cutlery",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/cutlery/",
  },
  {
    id: 4,
    name: "دستکش",
    slug: "gloves",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/gloves/",
  },
  {
    id: 5,
    name: "دستمال",
    slug: "tissues",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/tissues/",
  },
  {
    id: 6,
    name: "سفره",
    slug: "tablecloth",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/tablecloth/",
  },
  {
    id: 7,
    name: "ظروف آلومینیومی",
    slug: "aluminum-containers",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/aluminum-containers/",
  },
  {
    id: 8,
    name: "ظروف فومی",
    slug: "foam-containers",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/foam-containers/",
  },
  {
    id: 9,
    name: "لیوان",
    slug: "cups",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/cups/",
  },
  {
    id: 10,
    name: "نایلون",
    slug: "plastic",
    description: "",
    count: 0,
    image: null,
    parent: 0,
    permalink: "/product-category/plastic/",
  },
];
